version: '2.0'
services:
  home:
    container_name: homepage
    build: HomePage
    ports:
    - 5000:5000
    environment:
      - PORT=5000
  blog:
    container_name: blog
    build: Blog
    ports:
    - 5001:6000
    depends_on:
      - db
    environment:
      - PORT=6000
      - MONGO_PORT=27017
      - MONGO_HOST=db
    links:
      - db
  db:
    image: mongo
    ports:
    - 27019:27017
    - 27017:27017
